spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
app.sqs.queue-name=${SQS_OPERACAO_REGISTRADA_URL}
spring.cloud.aws.region.static=${AWS_REGION}
spring.cloud.aws.sqs.enabled=true
spring.datasource.driver-class-name=org.postgresql.Driver